version: "3.5"

services:
  server:
    image: server-chat
    restart: always
    build:
      context: ./server
      dockerfile: ${DOCKERFILE}
    container_name: server-chat
    volumes:
      - /app/node_modules
      - ./server:/app
    # ports:
    #   - 5000:5000
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_URI: ${MONGO_URI}
    networks:
      - chat-app
  client:
    image: client-chat
    container_name: client-chat
    restart: always
    build:
      context: ./client
      dockerfile: ${DOCKERFILE}
    volumes:
      - /app/node_modules
      - ./client:/app
    # ports:
    #   - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
    networks:
      - chat-app
  nginx:
    image: nginx-chat
    container_name: nginx-chat
    restart: always
    depends_on:
      - server
      - client
    build:
      context: ./nginx
      dockerfile: ${DOCKERFILE}
      network: host
      args:
        - CERTBOT_EMAIL=nhockrong98@gmail.com
        - DOMAIN_LIST=library-mern.tk
    ports:
      - "80:80"
      - "443:443"
    networks:
      - chat-app

networks:
  chat-app:
    driver: bridge
